name: Upload JVM Heapdumps
description: Upload JVM Heapdumps

runs:
  using: composite
  steps:
    - id: upload-jvm-heapdumps
      name: Upload JVM Heapdumps
      if: runner.os != 'Windows'
      uses: actions/upload-artifact@v4
      with:
        name: jvm-heap-dumps
        path: |
          '**/java_pid*.hprof'
          !distribution/**
        if-no-files-found: ignore