name: Build Keycloak
description: Builds Keycloak providing Maven repository with all artifacts

runs:
  using: composite
  steps:
    - id: maven-cache
      name: Maven cache
      uses: ./.github/actions/maven-cache
      with:
        create-cache-if-it-doesnt-exist: true

    - name: Grant execute permission to Gradle
      shell: bash
      run: chmod +x ./gradlew

    - id: build
      name: Build & Test Keycloak
      shell: bash
      run: |
        ./gradlew clean build --configuration-cache --build-cache --scan
