name: Keycloak Client CI

on:
  push:
    branches-ignore:
      - main
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Run Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Keycloak
        uses: ./.github/actions/build-keycloak

      - name: Upload JVM HeapDumps
        if: always()
        uses: ./.github/actions/upload-heapdumps


