name: Release to Maven Central portal

on:
  push:
    branches:
      - release/**

jobs:
  publish:
    name: Publish Maven Artifacts
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
#
#      - name: Build Keycloak
#        uses: ./.github/actions/build-keycloak
      - name: Decode GPG key
        run: |
          echo "$SIGNING_KEY" | base64 --decode > secret.asc
          gpg --batch --import secret.asc
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}

      - name: Grant execute permission to Gradle
        shell: bash
        run: chmod +x ./gradlew

      - name: Publish to Maven Central
        env:
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        run: |
          ./gradlew publishAllPublicationsToMavenCentralRepository \
            -PmavenCentralUsername="$MAVEN_CENTRAL_USERNAME" \
            -PmavenCentralPassword="$MAVEN_CENTRAL_PASSWORD" \
            -Psigning.secretKey="$SIGNING_KEY" \
            -Psigning.keyId="$SIGNING_KEY_ID" \
            -Psigning.password="$SIGNING_PASSWORD"


      - name: Upload JVM HeapDumps
        if: always()
        uses: ./.github/actions/upload-heapdumps


